dvb_hdhomerun-objs := dvb_hdhomerun_control.o dvb_hdhomerun_data.o dvb_hdhomerun_init.o
obj-$(CONFIG_DVB_HDHOMERUN) += dvb_hdhomerun.o

obj-$(CONFIG_DVB_HDHOMERUN) += dvb_hdhomerun_core.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/ -Idrivers/media/dvb/frontends
